package controller;

public enum Menu {
	MAIN, CUSTOMERS, BANKACCOUNTS, TRANSACTIONS, CUST_SEARCH, BACC_SEARCH, 
	CUST_CREATE_NAME, CUST_CREATE_SURNAME, CUST_CREATE_DOB, 
	CUST_CREATE_ADDRESS, CUST_CREATE_PHONE, CUST_CREATE_EMAIL, 
	CUST_CREATE_FINAL, CUST_DETAILS, 
	BACC_CREATE, BACC_CREATE_FINAL, BACC_DETAILS;
}
